# Generated by Django 3.2.23 on 2024-03-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFrontState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_invalidate_during_next_cron_tick', models.BooleanField(default=False)),
            ],
        ),
    ]
