# Generated by Django 3.2.23 on 2024-03-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tool_tag',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='tools.Tool', verbose_name='Associated Tools'),
        ),
        migrations.AddField(
            model_name='post',
            name='version_tag',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='tools.Version', verbose_name='Associated Versions'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='Post'),
        ),
    ]
