# Generated by Django 3.2.23 on 2024-03-27 19:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('static_page', '0001_initial'),
        ('blog_wagtail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='featured_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='static_page.captionedimage'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='posts', to='blog_wagtail.Topic'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='static_page.captionedimage'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('slug', 'locale_id'), ('translation_key', 'locale')},
        ),
    ]
