# Generated by Django 3.2.23 on 2024-03-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='app',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='installed_versions', to='tools.version', verbose_name='Installed App'),
        ),
    ]
