version: '3'

services:
    server:
        build: .
        command: ./manage.py runserver 0.0.0.0:8001
        ports:
            - "8001:8001"
        volumes:
            - ./paskoocheh:/usr/src/app
        depends_on:
            - db
        networks:
            - backend
        env_file:
            - ./.env
        environment:
            - DEBUG=1
            - DATABASE_HOST=db
            - 'SECRET_KEY=SeCrEtKeY'
            - DATABASE_USER=paskoocheh
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=paskoocheh
            - DATABASE_PORT=5432
            - ELASTICSEARCH_HOST=elasticsearch
            - ELASTICSEARCH_PORT=9200
            - PLATFORM=paskoocheh

    db:
        image: postgres:11
        ports:
            - "5432:5432"
        volumes:
            - ./private/postgres-data:/var/lib/postgresql/data
        networks:
            - backend
        environment:
            - POSTGRES_USER=paskoocheh
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=paskoocheh

    db-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: alias@mail.com
            PGADMIN_DEFAULT_PASSWORD: alias
        volumes:
            - ./private/pgadmin:/var/lib/pgadmin
        depends_on:
            - db
        ports:
            - "8080:80"
        networks:
            - backend

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - backend
        environment:
            - POSTGRES_USER=paskoocheh
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=paskoocheh


networks:
    backend:
        driver: bridge
